ballerina-platform/module-ballerina-oauth2

.github/workflows/build-master.yml, README.md, oauth2-ballerina/build.gradle
This PR updates the readme of the repository with the required configurations to run `./gradlew test` command.
=> Update readme and configurations

oauth2-ballerina/src/oauth2/inbound_oauth2_provider.bal, oauth2-ballerina/src/oauth2/outbound_oauth2_provider.bal
=> Fix oauth2 module for object syntax change

.github/workflows/pull-request.yml
=> Update GitHub actions

.github/workflows/publish-release.yml, build.gradle, oauth2-ballerina/build.gradle
=> Update GitHub release workflow

oauth2-ballerina/src/oauth2/inbound_oauth2_provider.bal, oauth2-ballerina/src/oauth2/oauth2_errors.bal, oauth2-ballerina/src/oauth2/outbound_oauth2_provider.bal
$subject
Fixes: https://github.com/ballerina-platform/module-ballerina-oauth2/issues/9
=> Update oauth2 module with isolated functions

.github/workflows/build-master.yml, .github/workflows/daily-build.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, README.md
=> Migrate to JDK11

build.gradle
=> Remove unused extra properties

oauth2-ballerina/src/oauth2/inbound_oauth2_provider.bal, oauth2-ballerina/src/oauth2/outbound_oauth2_provider.bal
$subject
https://docs.google.com/document/d/161cAqT_AbH4b95k6itdRrgqWbSSC14FGuMNo6Blbrw8/edit
=> Fix for HTTP client API changes

oauth2-ballerina/build.gradle
$subject related to https://github.com/ballerina-platform/module-ballerina-oauth2/pull/34
=> Exclude adding file pattern to cache

oauth2-ballerina/build.gradle
=> Enable copying of dependency caches and doc generation

build.gradle, oauth2-ballerina/build.gradle
=> Refactor gradle configurations

oauth2-ballerina/inbound_oauth2_provider.bal, oauth2-ballerina/oauth2_errors.bal, oauth2-ballerina/outbound_oauth2_provider.bal
=> Update log level to error

oauth2-ballerina/init.bal, oauth2-native/src/main/java/org/ballerinalang/stdlib/oauth2/Constants.java, oauth2-native/src/main/java/org/ballerinalang/stdlib/oauth2/ModuleUtils.java, oauth2-native/src/main/java/org/ballerinalang/stdlib/oauth2/OAuth2Client.java
=> Replace hard coded native package version

oauth2-ballerina/listener_oauth2_provider.bal
=> Refactor introspection config record

oauth2-ballerina/client_oauth2_provider.bal, oauth2-ballerina/listener_oauth2_provider.bal, oauth2-ballerina/oauth2_errors.bal
=> Fix for syntax changes related to errors

oauth2-ballerina/client_oauth2_provider.bal, oauth2-ballerina/listener_oauth2_provider.bal
=> Refactor oauth2 related cache configurations 

oauth2-ballerina/client_oauth2_provider.bal, oauth2-ballerina/listener_oauth2_provider.bal
=> Update default token expiry time field

build.gradle, gradle.properties, oauth2-ballerina/Ballerina.toml, oauth2-ballerina/build.gradle, oauth2-ballerina/listener_oauth2_provider.bal
=> Replace usages of stringutils APIs

oauth2-ballerina/build.gradle
$subject.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Update ballerina command to bal command

oauth2-ballerina/Package.md
=> Update package md files

oauth2-ballerina/init.bal, oauth2-ballerina/oauth2_commons.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Change the name of the `java` langlib module to `jballerina.java`

README.md, oauth2-ballerina/client_oauth2_provider.bal, oauth2-ballerina/listener_oauth2_provider.bal, oauth2-ballerina/oauth2_errors.bal
=> Update ballerina documentations

oauth2-ballerina/Ballerina.toml, oauth2-ballerina/Dependencies.toml, oauth2-ballerina/build.gradle
Fixes ballerina-platform/ballerina-lang#27988
=> Add Dependencies.toml

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, oauth2-ballerina/build.gradle
=> Publish code coverage exec file as a maven artifact

oauth2-ballerina/build.gradle
=> Refactor build task order

oauth2-ballerina/build.gradle
=> Avoid running tests twice when publishing

README.md, oauth2-ballerina/Package.md
=> Update docs for swan-lake URL change

build.gradle, oauth2-ballerina/build.gradle
=> Re-order build tasks to publish to ballerina central

oauth2-ballerina/build.gradle
$subject for https://github.com/ballerina-platform/module-ballerina-oauth2/pull/88
=> Update missing configurations

oauth2-ballerina/client_oauth2_provider.bal, oauth2-ballerina/listener_oauth2_provider.bal, oauth2-native/src/main/java/org/ballerinalang/stdlib/oauth2/OAuth2Client.java
=> Refactor error messages and debug logs

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, oauth2-ballerina/build.gradle
=> Remove publishing exec artifacts and archiving test json

oauth2-ballerina/client_oauth2_provider.bal, oauth2-ballerina/listener_oauth2_provider.bal
$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/967
=> Update fields representing time-units with the convention

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, README.md, codecov.yml
=> Add Codecov Report Generation

oauth2-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
=> Add extracted bala in the zip artifact

oauth2-ballerina/Package.md
$subject related to https://github.com/ballerina-platform/ballerina-distribution/pull/1376
=> Update Package.md for BBE update

gradle.properties, oauth2-ballerina/client_oauth2_provider.bal, oauth2-ballerina/listener_oauth2_provider.bal
=> Update for Time API changes

oauth2-ballerina/build.gradle
> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032
=> Add -c flag to build command

oauth2-ballerina/listener_oauth2_provider.bal
=> Update for Cache API changes

oauth2-ballerina/client_oauth2_provider.bal, oauth2-ballerina/listener_oauth2_provider.bal, oauth2-ballerina/tests/listener_oauth2_provider_test.bal
This PR remove the `checkpanic` keyword usages for type narrowing.
=> Remove usages of checkpanic for type narrowing

oauth2-ballerina/client_oauth2_provider.bal, oauth2-ballerina/listener_oauth2_provider.bal
This PR updates the log messages for a security concern.
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1203
=> Update log messages for a security concern

changelog.md, oauth2-ballerina/client_oauth2_provider.bal, oauth2-ballerina/listener_oauth2_provider.bal, oauth2-ballerina/tests/listener_oauth2_provider_test.bal, oauth2-native/src/main/java/org/ballerinalang/stdlib/oauth2/OAuth2Client.java
$subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1242
=> Improve error messages and log messages

build.gradle, oauth2-ballerina/build.gradle
=> Strip stdlib dependency version

oauth2-ballerina/build.gradle
=> Fix publishing workflow

oauth2-ballerina/build.gradle, oauth2-ballerina/tests/client_oauth2_provider_test.bal, oauth2-ballerina/tests/listener_oauth2_provider_test.bal
=> Update unit tests for compatibility with latest ballerina-sts

oauth2-ballerina/build.gradle
Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381
=> Set flag to enable Jacoco Coverage XML generation

.github/workflows/pull-request.yml, oauth2-ballerina/build.gradle, oauth2-ballerina/tests/client_oauth2_provider_test.bal, oauth2-ballerina/tests/listener_oauth2_provider_test.bal
=> Skip Docker based tests in Windows OS

README.md, oauth2-ballerina/Module.md, oauth2-ballerina/Package.md, oauth2-ballerina/build.gradle, oauth2-ballerina/client_oauth2_provider.bal, oauth2-ballerina/listener_oauth2_provider.bal, oauth2-ballerina/oauth2_errors.bal, oauth2-ballerina/tests/client_oauth2_provider_test.bal, oauth2-ballerina/tests/test_utils.bal
=> Improve the API documentation and markdown files

oauth2-ballerina/build.gradle
$subject
Related to https://github.com/ballerina-platform/module-ballerina-oauth2/pull/191
=> Fix a bug in gradle task order

oauth2-ballerina/client_oauth2_provider.bal, oauth2-ballerina/listener_oauth2_provider.bal, oauth2-ballerina/oauth2_commons.bal
=> Improve API docs

oauth2-ballerina/Package.md
This is a part of https://github.com/ballerina-platform/ballerina-standard-library/issues/1462
=> Update Package.md links into HTML format

ballerina/Module.md, ballerina/client_oauth2_provider.bal, ballerina/listener_oauth2_provider.bal, ballerina/oauth2_errors.bal, ballerina/tests/listener_oauth2_provider_test.bal, changelog.md, native/src/main/java/io/ballerina/stdlib/oauth2/OAuth2Client.java
=> Improve documentations

docs/spec/spec.md
Add specification for `ballerina/oauth2` library.
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2209
=> Add oauth2 library specification

examples/order-management-service/README.md
=> Fix examples for SL-Beta4 changes

examples/order-management-service/api_gateway/api_gateway.bal, examples/order-management-service/app_backend/app_backend.bal, load-tests/order_management_service/src/api_gateway.bal
=> Improve load-tests and examples

examples/order-management-service/api_gateway/api_gateway.bal, examples/order-management-service/app_backend/app_backend.bal, load-tests/order_management_service/src/api_gateway.bal
$subject related to https://github.com/ballerina-platform/module-ballerina-oauth2/pull/377
=> Fix imports

examples/order-management-service/app_backend/app_backend.bal
$subject related to https://github.com/ballerina-platform/module-ballerina-oauth2/pull/377
=> Fix a bug in examples

ballerina/client_oauth2_provider.bal, ballerina/listener_oauth2_provider.bal, ballerina/oauth2_errors.bal, ballerina/tests/client_oauth2_provider_test.bal, ballerina/tests/listener_oauth2_provider_test.bal, ballerina/tests/test_utils.bal
$subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2201
=> Refactor code base

ballerina/tests/client_oauth2_provider_test.bal
$subject fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2196
=> Improve unit tests with negative tests

ballerina/build.gradle, ballerina/tests/client_oauth2_provider_test.bal, ballerina/tests/listener_oauth2_provider_test.bal, changelog.md, native/src/main/java/io/ballerina/stdlib/oauth2/OAuth2Client.java, native/src/main/java/io/ballerina/stdlib/oauth2/OAuth2Constants.java
$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2816
=> Improve appending scheme part of the HTTP client URL

ballerina/listener_oauth2_provider.bal, ballerina/oauth2_errors.bal
$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3026
N/A
=> Convert error logs to debug logs

ballerina/Ballerina.toml, ballerina/Dependencies.toml, gradle.properties
=> Update version to 2.4.0-SNAPSHOT

.github/workflows/update_spec.yml
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3154
=> Add stdlib specs update workflow

docs/spec/spec.md
=> Fix inconsistencies in spec

ballerina/Dependencies.toml, build.gradle, gradle.properties
=> Update cache version

ballerina/Ballerina.toml, ballerina/Dependencies.toml
=> [Automated] Update the native jar versions

ballerina/Dependencies.toml, gradle.properties
Fixes: [#3414](https://github.com/ballerina-platform/ballerina-standard-library/issues/3414)
=> Update dependency versions to support native-image tool

ballerina/tests/client_oauth2_provider_test.bal, changelog.md, native/src/main/java/io/ballerina/stdlib/oauth2/OAuth2Client.java
Fixes: [#3402](https://github.com/ballerina-platform/ballerina-standard-library/issues/3402)
=> Fix throwing java exception for invalid tokenUrl 

README.md, ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/Package.md, build-config/resources/Ballerina.toml, changelog.md, docs/spec/spec.md, gradle.properties
$Subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/3463
=> Replace slack channel link and dependent module versions

ballerina/Ballerina.toml, ballerina/Dependencies.toml, gradle.properties
=> Update version to 2.4.1

.github/workflows/build-with-bal-test-native.yml, README.md, gradle.properties
Part of : https://github.com/ballerina-platform/ballerina-standard-library/issues/3316
=> Add bal test native workflow

ballerina/Ballerina.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517
=> Update versions for type-reference-support #

ballerina/Dependencies.toml, ballerina/client_oauth2_provider.bal, ballerina/tests/client_oauth2_provider_test.bal, ballerina/tests/listener_oauth2_provider_test.bal, changelog.md, docs/spec/spec.md
Fixes: [#3879](https://github.com/ballerina-platform/ballerina-standard-library/issues/3879)
Fixes: [#3877](https://github.com/ballerina-platform/ballerina-standard-library/issues/3877)
=> Allow password grant type to refresh token using the inferred values and Allow string value for scopes field

.github/workflows/pull-request.yml
$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3988
=> Retry codecov upload on failure

ballerina/Dependencies.toml, gradle.properties
=> Update timestamp version

ballerina/build.gradle
Related to : https://github.com/ballerina-platform/ballerina-standard-library/issues/4021
=> Optimize build script to skip docker tasks when using the `-x test` flag

.github/workflows/central-publish.yml
=> Update central-publish workflow

.github/workflows/pull-request.yml
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4221
=> Introduce concurrency setting

ballerina/Ballerina.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Update dependency versions for update-5

ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/tests/test_utils.bal, build.gradle, gradle.properties
$Subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/4382
=> Remove regex package usage

gradle.properties
=> Update log package version to latest timestamp version

load-tests/order_management_service/src/Cloud.toml
Temporarily  fix the issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4414
=> Temporarily increase load-test resources

.github/workflows/build-with-bal-test-graalvm.yml, README.md, ballerina/Ballerina.toml, ballerina/Dependencies.toml, gradle.properties
Part of : https://github.com/ballerina-platform/ballerina-standard-library/issues/4548
=> Incorperate native build command change

ballerina/Ballerina.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
Part of : https://github.com/ballerina-platform/ballerina-standard-library/issues/4568
=> Mark oauth2 module as GraalVM compatible

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, .github/workflows/update_spec.yml, README.md, build-config/checkstyle/build.gradle, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, settings.gradle
=> Migrate to java 17

ballerina/Ballerina.toml, build-config/resources/Ballerina.toml
=> Update Java dependency to jdk-17

examples/order-management-service/A Guideline on Securing Ballerina REST APIs.md
This is for SEO purposes so the examples get listed on search engines.
=> Update README file of the example

ballerina/Ballerina.toml, ballerina/Dependencies.toml, gradle.properties
=> Bump the Dependency Versions

ballerina/Ballerina.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Change the distribution version to 2201.9.0

ballerina/tests/client_oauth2_provider_test.bal
Related issue: https://github.com/ballerina-platform/ballerina-library/issues/6480
=> Disable the failing test case

ballerina/Ballerina.toml, ballerina/Dependencies.toml, gradle.properties
=> Update minor version

load-tests/order_management_service/src/Cloud.toml
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6967
=> Update cmd to entrypoint in Cloud.toml

.github/workflows/build-timestamped-master.yml, .github/workflows/build-with-bal-test-graalvm.yml, .github/workflows/central-publish.yml, .github/workflows/process-load-test-result.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trigger-load-tests.yml, .github/workflows/trivy-scan.yml, README.md, ballerina/Ballerina.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, build.gradle, gradle.properties, native/build.gradle
=> Migrate to Java 21

ballerina/Dependencies.toml, ballerina/tests/client_oauth2_provider_test.bal, ballerina/tests/listener_oauth2_provider_test.bal
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7410
=> Enable the disabled test cases during update 11 migration

ballerina/Ballerina.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, build.gradle, gradle.properties
=> Prepare for Update 13 release
